# Generated by Django 3.2.8 on 2021-11-24 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_oauth_app', '0002_alter_task_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='class_number',
        ),
        migrations.RemoveField(
            model_name='course',
            name='class_section',
        ),
        migrations.RemoveField(
            model_name='course',
            name='class_topic_formal_desc',
        ),
        migrations.RemoveField(
            model_name='course',
            name='enrollment_capacity',
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='meeting_days',
        ),
        migrations.RemoveField(
            model_name='course',
            name='meeting_time_end',
        ),
        migrations.RemoveField(
            model_name='course',
            name='meeting_time_start',
        ),
        migrations.RemoveField(
            model_name='course',
            name='term',
        ),
        migrations.RemoveField(
            model_name='course',
            name='term_desc',
        ),
    ]
